# Generated by Django 5.2.8 on 2026-01-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_resAb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='id_column_data',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='arbol',
            name='text_column',
            field=models.CharField(default='', max_length=60),
        ),
    ]
