# Generated by Django 5.2.8 on 2026-01-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_resAb', '0002_arbol_id_column_data_arbol_text_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='tree_structure',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
