# Generated by Django 5.2.8 on 2026-02-12 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='graphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data_path', models.CharField(max_length=255)),
                ('file_embedding_path', models.CharField(max_length=255)),
                ('text_column', models.CharField(default='', max_length=50)),
                ('id_column', models.CharField(default='', max_length=20)),
                ('graph_structure', models.JSONField(default=dict, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.users')),
            ],
        ),
    ]
