# Generated by Django 5.2.8 on 2026-03-09 20:52

import django.db.models.deletion
from django.db import migrations, models


def delete_old_relationships(apps, schema_editor):
    """Elimina las 5 relaciones hardcodeadas y sus aristas en cascada."""
    relationship = apps.get_model('back', 'relationship')
    relationship.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False  # Necesario: el RunPython (DELETE CASCADE) y los AddField (CREATE INDEX) no pueden coexistir en la misma transacción

    dependencies = [
        ('back', '0003_graphs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='color',
            field=models.CharField(default='#6366f1', max_length=20),
        ),
        migrations.AddField(
            model_name='relationship',
            name='direction',
            field=models.CharField(default='forward', max_length=20),
        ),
        migrations.AddField(
            model_name='relationship',
            name='graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.graphs'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.users'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='is_dashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='is_global',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relationship',
            name='stroke_width',
            field=models.IntegerField(default=2),
        ),
        migrations.RunPython(delete_old_relationships, migrations.RunPython.noop),
    ]
