# Generated by Django 5.2.8 on 2026-03-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_relationship_color_relationship_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='pos_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='pos_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
