# Generated by Django 5.2.8 on 2026-03-17 01:57

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_nodes_pos_x_nodes_pos_y'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;", migrations.RunSQL.noop),
        migrations.RemoveField(
            model_name='graphs',
            name='file_embedding_path',
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_data', models.CharField(max_length=20)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ('block', models.BooleanField(default=False)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.graphs')),
            ],
        ),
        migrations.CreateModel(
            name='Nodes_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.data')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.nodes')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='nodes',
            field=models.ManyToManyField(blank=True, through='back.Nodes_Category', to='back.nodes'),
        ),
        migrations.AddIndex(
            model_name='nodes_category',
            index=models.Index(fields=['data'], name='idx_nc_data'),
        ),
        migrations.AddIndex(
            model_name='nodes_category',
            index=models.Index(fields=['node'], name='idx_nc_node'),
        ),
        migrations.AlterUniqueTogether(
            name='nodes_category',
            unique_together={('node', 'data')},
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['graph'], name='idx_data_graph'),
        ),
    ]
