# Generated by Django 5.2.8 on 2026-03-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_remove_graphs_file_embedding_path_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='graphs',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
