# Generated by Django 5.2.8 on 2026-04-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_graphs_status_graphs_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
